version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
